apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: erpnext
  namespace: erpnext-v1
spec:
  interval: 1m
  releaseName: frappe-bench
  chart:
    spec:
      chart: ./erpnext
      sourceRef:
        kind: GitRepository
        name: erpnext
  values:
   persistence:
    worker:
      storageClass: nfs-csi
   mariadb:
    primary:
     persistence:
      enabled: false

